project:
  type: website
  output-dir: docs

website:
  title: "Eunkyung Yi"
  site-url: "https://yieunkyung.github.io"
  sitemap: true

format:
  html:
    theme: minty
    css: styles.css
    toc: false
    anchor-sections: false


